### ISSUE TITLE
Why I use the same method mentioned in the README to preprocess the spider data, but I can not load the checkpoint you provide.

### ISSUE THREAD

**Issue by eyuansu62** [taoyds/grappa#4]

**Comment by taoyds** [comment]
I'm not sure if you got this issue. We used the early version of RATSQL. The error might come from their code update. Maybe you can download our [processed Spider data](https://drive.google.com/file/d/1QIM1VswEvbYhUK3mP8f3ed0ZDGrCj1SK/view?usp=sharing).
